from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/8037099/files/subread_2.0.3.img"

rule all:
    input: ["counts.tsv"]

rule feature_counts:
    input:
        bam="test.sorted.bam",
        gff="test.gff"
    output:
        counts="counts.tsv",
        summary="counts.tsv.summary"
    log:
        "logs/feature_counts.log"
    params:
        options="",
        strandness=0,
        feature="gene",
        attribute="ID"
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("feature_counts/run", "v1")
