from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["quant/sample/quant.sf"]

rule salmon_index:
    input:
        fasta="data/genome.fa",
        gff="data/genome.gff3"
    output:
        done="salmon_index/done"
    log:
        "logs/salmon_index.log"
    params:
        options=""
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("salmon/index", "v1")

rule salmon_align:
    input:
        fastq=["data/test_R1.fastq.gz", "data/test_R2.fastq.gz"],
        index="salmon_index/done"
    output:
        quant="quant/sample/quant.sf"
    log:
        "logs/salmon_align.log"
    params:
        options="-l A"
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("salmon/align", "v1")
