from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["test.fastq.gz"]

rule dsrc_to_gz:
    input:
        "test.fastq.dsrc"
    output:
        "test.fastq.gz"
    log:
        "logs/dsrc_to_gz.log"
    params:
        options=""
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("dsrc_to_gz/run", "v1")
