from sequana_wrappers import get_shell

rule all:
    input: ["a/a.sorted.bam"]

rule minimap2:
    input:
        fastq=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        reference="genome.fasta"
    output:
        "{sample}/{sample}.sorted.bam"
    log:
        "{sample}/{sample}.log"
    params:
        options=""
    threads: 2
    container:
        "https://zenodo.org/record/19127803/files/sequana_minimal_26.3.19.img"
    shell:
        get_shell("minimap2/align", "v1")
