rule multiqc:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a", "b"])
    output:
        "qc/multiqc.html"
    params:
        options="",
        input_directory=".",
        config_file="",
        modules=""
    log:
        "logs/multiqc.log"
    wrapper:
        "main/wrappers/multiqc"
