rule multiqc:
    input:
        expand("samtools_stats/{sample}.txt", sample=["a", "b"])
    output:
        "qc/multiqc.html"
    params:
        option=""
    log:
        "logs/multiqc.log"
    wrapper:
        "main/wrappers/multiqc"
