rule all:
    input: "raw/ctg.fa"

rule spades:
    input: 
        fastq=["raw_R1.fastq.gz"]
    output:
        contigs="raw/ctg.fa",
        scaffolds="raw/scf.fa"
    params:
        k=21,
        preset="isolate",
        options="--only-assembler",
        memory=4
    log:
        "spades.log"
    wrapper:
        "main/wrappers/spades"