

rule all:
    input:
        "star_mapping/_Aligned.sortedByCoord.out.bam",
        "star_mapping2/_Aligned.sortedByCoord.out.bam",

rule star_mapping:
    input:
        fastq="test.fastq.gz",
        reference="genome.fasta",
        index="star_index/star.done"
    output:
        bam="star_mapping/_Aligned.sortedByCoord.out.bam"
    params:
        legacy=True,
    threads: 1
    log:
        "star_mapping/star.log"
    wrapper:
        "main/wrappers/star/align"


rule star_mapping2:
    input:
        fastq="test.fastq.gz",
        reference="genome.fasta",
        index="star_index/star.done",
        annotation="genome.gff3"
    output:
        bam="star_mapping2/_Aligned.sortedByCoord.out.bam"
    params:
        exonParentTranscript='Parent'
    threads: 1
    log:
        "star_mapping2/star.log"
    wrapper:
        "main/wrappers/star/align"





