from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["assembly/ctg.fa"]

rule unicycler:
    input:
        fastq=["raw_R1.fastq.gz"]
    output:
        fasta="assembly/ctg.fa"
    log:
        "logs/unicycler.log"
    params:
        mode="normal",
        long_reads="False",
        options=""
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("unicycler/run", "v1")
