
rule all:
    input:
        "polypolish/polypolish1.fasta",
        "polypolish/polypolish2.fasta",
        "polypolish/polypolish3.fasta"


# test with named input parameters and specific params 
rule polypolish1:
    input:
        alignment="alignments.sam",
        assembly="assembly.fasta"
    output:
        fasta = "polypolish/polypolish1.fasta"
    params:
        options= "  ",
    log:
        "polypolish/test1.log"
    wrapper:
        "main/wrappers/polypolish"


# test with named input parameters and default params
rule polypolish2:
    input:
        alignment="alignments.sam",
        assembly="assembly.fasta"
    output:
        fasta = "polypolish/polypolish2.fasta"
    log:
        "polypolish/test2.log"
    wrapper:
        "main/wrappers/polypolish"


# test with list of input parameters and default params
rule polypolish3:
    input:
        "alignments.sam",
        "assembly.fasta"
    output:
        fasta = "polypolish/polypolish3.fasta"
    log:
        "polypolish/test3.log"
    wrapper:
        "main/wrappers/polypolish"
