from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/17098202/files/snpeff_5.2.0.img"
CONTAINER = "https://zenodo.org/record/7963301/files/snpeff_5.1.0.img"

rule all:
    input: ["test.ann.vcf"]

rule snpeff:
    input:
        vcf="test.raw.vcf",
        ann="measles.gbk"
    output:
        vcf="test.ann.vcf",
        csv="test.ann.csv",
        html="snpeff.html"
    log:
        "logs/snpeff.log"
    params:
        options="",
        genome_name="measles"
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("snpeff/run", "v1")
