from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["data_R1_.dnpe.fastq", "data_R2_.dnpe.fastq"]

rule digital_normalisation:
    input:
        fastq=["data_R1_.fastq.gz", "data_R2_.fastq.gz"]
    output:
        r1="data_R1_.dnpe.fastq",
        r2="data_R2_.dnpe.fastq"
    log:
        "logs/digital_normalisation.log"
    params:
        ksize=20,
        cutoff=20,
        m=1000000000,
        tmp_graph_name="graph.ct",
        options=""
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("digital_normalisation/run", "v1")
