from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/10211475/files/bamtools_2.5.2.img"

rule all:
    input: ["sample/sample.bam.bai"]

rule bamtools_index:
    input:
        bam="sample/sample.bam"
    output:
        bai="sample/sample.bam.bai"
    log:
        "logs/bamtools_index.log"
    params:
        options=""
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("bamtools/index", "v1")
