rule all:
    input: 
        "test.dt"

rule rulegraph:
    input:
        workflow.snakefile
    output:
        "test.dt"
    params:
        mapper = {'rulegraph': 'rulegraph.html'},
        required_local_file = ['schema.yml',],
        configname = 'config.yml'
    wrapper:
        "main/wrappers/rulegraph"
