from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["prokka/ctg.gff"]

rule prokka:
    input:
        assembly="ctg.fa"
    output:
        "prokka/ctg.gff"
    log:
        "logs/prokka.log"
    params:
        options=""
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("prokka/run", "v1")
