
rule all:
    input: "test.fastq.gz"


rule dsrc_to_gz:
    input:
        "test.fastq.dsrc"
    output:
        "test.fastq.gz"
    threads: 2
    params: "-m2"
    wrapper:
        "main/wrappers/dsrc_to_gz"
