#rule all:
#    input: ["mapped/a.bam", "mapped/bowtie2_sorted/a.sorted.bam"]

rule bowtie2_sorted:
    input:
        fastq=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        idx=multiext(
            "index/genome",
            ".1.bt2",
            ".2.bt2",
            ".3.bt2",
            ".4.bt2",
            ".rev.1.bt2",
            ".rev.2.bt2",
        ),
    output:
        bam="mapped/{sample}.sorted.bam"
    log:
        "logs/bowtie2/{sample}.log"
    params:
        options=""  # optional parameters
    threads: 2  # Use at least two threads
    wrapper:
        "main/wrappers/bowtie2/align"
