from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/17097941/files/fastp_1.0.1.img"

rule all:
    input: ["trimmed/a.1.fastq", "trimmed/a.2.fastq"]

rule fastp:
    input:
        fastq=["../data/reads/a.1.fastq", "../data/reads/a.2.fastq"]
    output:
        r1="trimmed/a.1.fastq",
        r2="trimmed/a.2.fastq",
        html="report/a.html",
        json="report/a.json"
    log:
        "logs/fastp.log"
    params:
        options="",
        adapters=""
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("fastp/run", "v1")
