from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img"

rule all:
    input: ["test.bw"]

rule bam_coverage:
    input:
        bam="test.bam"
    output:
        "test.bw"
    log:
        "logs/bam_coverage.log"
    params:
        options=""
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("deeptools/bam_coverage", "v1")
