from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/8037162/files/sequana_minimal_23.6.13.img"

rule all:
    input: ["test.filtered.bam"]

rule sambamba_filter:
    input:
        bam="test.bam"
    output:
        bam="test.filtered.bam"
    log:
        "logs/sambamba_filter.log"
    params:
        options="",
        threshold=30
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("sambamba_filter/run", "v1")
