rule minimap2:
    input:
        fastq=["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        reference="genome.fasta"
    output:
        sorted="{sample}/{sample}.sorted.bam"
    log:
        "{sample}/{sample}.log"
    params:
        options=""
    threads: 2
    wrapper:
        "main/wrappers/minimap2"

