rule all:
    input: "raw/ctg.fa"

rule unicycler:
    input: 
        fastq=["raw_R1.fastq.gz"]
    output:
        fasta="raw/ctg.fa",
        #gfa="raw/ctg.gfa"
    log:
        "unicycler.log"
    wrapper:
        "main/wrappers/unicycler"

