from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/7437898/files/samtools_1.16.1.img"

rule all:
    input: ["test.bed"]

rule samtools_depth:
    input:
        bam="test.sorted.bam"
    output:
        "test.bed"
    log:
        "logs/samtools_depth.log"
    params:
        options=""
    threads: 2
    container:
        CONTAINER
    shell:
        get_shell("samtools_depth/run", "v1")
