rule sambamba_filter:
    input:
        "test.sorted.bam"
    output:
        bam="test.filter.bam",
    log: "sambamba_filter.log"
    params:
        threshold=30
    wrapper:
        "main/wrappers/sambamba_filter"


