rule sambamba_filter:
    input:
        "test.sorted.bam"
    output:
        bam="test.filter.bam",
    log:
        out = "log.out",
        err = "log.err"
    params:
        threshold=30,
        options=""
    wrapper:
        "main/wrappers/sambamba_filter"


