
rule all:
    input:
        "fastq_stats/test_R1_.json"

rule fastq_stats:
    input:
        "{sample}.fastq.gz"
    output:
        "{sample}/fastq_stats/{sample}.json"
    params:
        wkdir="fastq_stats",
        max_reads=500000
    wrapper:
        "main/wrappers/fastq_stats"


