from sequana_wrappers import get_shell

CONTAINER = "https://zenodo.org/record/13732628/files/polypolish_0.6.0.img"

rule all:
    input: ["filtered/assembly.fasta"]

rule polypolish:
    input:
        assembly="assembly.fasta",
        alignments="alignments.sam"
    output:
        fasta="filtered/assembly.fasta"
    log:
        "logs/polypolish.log"
    params:
        options=""
    threads: 4
    container:
        CONTAINER
    shell:
        get_shell("polypolish/polish", "v1")
