

rule all:
    input: 
        "test/md.bam"



rule mark_duplicates:
    input:
        "test.sorted.bam"
    output:
        bam = "test/md.bam",
        metrics = "test/md.metrics"
    log:
        out = "test/log.out",
        err = "test/log.err"
    params:
        remove_dup = "false",
        tmpdir = "test/tmp"
    wrapper:
        "main/wrappers/mark_duplicates"


